title: Weather App Homepage
page-top-title: CSCE 625 Artificial Intelligence
top-section-bg-text: Agentic AI for Disaster Response: Real-Time, Multi-Modal Reasoning at the Edge of Emergency Management
home-subtitle: INTRODUCTION
copyright-text: '&copy; Sai Kiran Dyavadi | Sirisha NK | Rishitha Nimma 2025-2026. All Rights Reserved.'
